### PR TITLE
My PPV changes

### PR DESCRIPTION
**Pull request by Fyb3roptik**

### CODE REVIEW

**Comment by Fyb3roptik** [comment]
This not only adds PPV but also adds Github Actions Builds

**Comment by SCP002** [comment]
Alright, v2.5.0 got released yesterday (was closing the final ones just before this PR), decided to not to merge this just before release, without review, possibly introducing breaking changes.

Now, I don't plan any futurer changes into the actual source code. The only things will be updated are dockerfile and readme's (https://github.com/SCP002/xTeVe/issues/36), but not xTeVe's internals.
After docker version is out, planning to archivate this repository.

And because your fork would probably use your own docker container anyway (if you wish to mess with docker ofcourse), IMHO it's already fine if you fork my repo and make any changes you would like to, because nothing important related to your new fork will change anyway.

A few notices:

* Maybe you would like to remove my PPV implementation and replace with your own. If so, here is the list of changes https://github.com/SCP002/xTeVe/compare/d4be1ce...b1cda6d, https://github.com/SCP002/xTeVe/compare/1a23592...da45ced to make it easier for you to remove it. Core logic is here: https://github.com/SCP002/xTeVe/blob/a708be072eecd2a3655a04668f35b494fe4d7c98/src/xepg.go#L388-L421
If your implementation do not keep the original channel number and preserving them is important (IDK; because such behavior was requested here https://github.com/SCP002/xTeVe/issues/38), you might keep both of our solutions.

* I've noticed in github action files the go version specified is 1.15 however this fork only works with 1.18+.

* Revently I've added the "Mapping" section to settings page, maybe it would be better to move your PPV checkbox under this new category, but it's up to you to decide :)

**Comment by Fyb3roptik** [comment]
Ah yes I can fix GHA and the settings location for sure. I would like to see your docker stuff as well so maybe ill wait on the fork. If youre on discord or Element or something let me know and we can communicate when youre done

**Comment by Fyb3roptik** [comment]
Also did you mean to close this PR?

**Comment by SCP002** [comment]
@Fyb3roptik Been away for 2 days + spent a 1,5 days learning what is docker, how to build my image etc.

Added docker image with https://github.com/SCP002/xTeVe/compare/e120f5b...70f4c97, check it out https://github.com/SCP002/xTeVe#docker

Please don't get me wrong, and no offence, but merging this PR assumes I should review it, check if everything is working, figure out if everything is working the way it was requested in #38, make a new build, upload it and supply with release notes.

The same with communicating. Communication assumes you'll ask me a questions about this codebase, which will turn out in spending time reading it and recalling how it was made.
There is another way to figure out which piece of code does what: Every release in this repo contains descriptions with every change mapped to corresponding commits. This will help greatly IMO.

As I've told before, it's time to switch to another project for me. And I absolutely dont mind if you fork this fork 🙃, rewire it the way you like, replace all occurences of `SCP002` with `Fyb3roptik` and make your own build. As well as your own Docker image if you'ld like.

Once again, sorry if I sound a little bit rude. Honestly nothing personal 🙂

**Pull request closed without merging**
